apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      #the port that other services could connect to this pod
      targetPort: 3000
      #the port taat map into the docker
      nodePort: 31515
      #port to acces this pod from our computer
  selector:
    #service look on the selector and route the request to the match pod
    component: web
