apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
    #label connect beetwen service and pod mapping
spec:
  containers:
    - name: client
      image: stephengrider/client-worker
      ports:
        - containerPort: 3000
